version: '3.9'

services:

  shipping:
    image: maven:3.9-amazoncorretto-19
    container_name: shipping
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - spring_microservices

volumes:
  maven-repo:

networks:
  spring_microservices:
    external: true
